--函数
--函数注重的是返回结果
--语法
CREATE OR REPLACE FUNCTION F_ST_SCORE()
RETURN NUMBER;


--案例
--FUNCTION  函数关键字
--GET_AVG 函数名字
--RETURN NUMBER  返回类型
CREATE OR REPLACE FUNCTION GET_AVG(DEPT_NO NUMBER) RETURN NUMBER
IS
V_AVGSAL NUMBER;
BEGIN
SELECT AVG(SAL) INTO V_AVGSAL FROM EMP WHERE DEPTNO = DEPT_NO;
RETURN V_AVGSAL;
END;


--函数调用
--第一种调用方式
SELECT GET_AVG(10) FROM DUAL;

--第二种方式
DECLARE
V_AVGSAL NUMBER;
BEGIN
    V_AVGSAL := GET_AVG(10);
    DBMS_OUTPUT.PUT_LINE ('V_AVGSAL' || V_AVGSAL);
END;


--根据部门编码和职位得到员工人数
--创建函数
CREATE OR REPLACE FUNCTION GET_NUM(V_DEPTNO NUMBER,V_JOB VARCHAR2) RETURN NUMBER
IS
   V_NUM NUMBER;
BEGIN
SELECT COUNT(*) INTO V_NUM FROM EMP WHERE DEPTNO = V_DEPTNO AND JOB = V_JOB;
RETURN V_NUM;
END;


--调用函数
SELECT GET_NUM(20,'CLERK') FROM DUAL ;

--删除函数
DROP FUNCTION GET_NUM ;



