--存储过程
--存储过程注重过程
CREATE [OR REPLACE] PROCEDURE 名字 (PARAM1 IN  TYPE,PARAM2 OUT TYPE)
IS
过程体

SELECT * FROM T_DEPT


--案例
CREATE OR REPLACE PROCEDURE P_ADD_DEPT
(D_NAME IN VARCHAR2,D_LOC IN VARCHAR2)
AS
   V_DEPTNO NUMBER;
BEGIN
SELECT MAX(DFFF) INTO V_DEPTNO FROM T_DEPT;
V_DEPTNO := V_DEPTNO +10;
INSERT INTO T_DEPT (DEPTNO,DNAME,LOC) VALUES(V_DEPTNO,D_NAME,D_LOC);
COMMIT;
END;

DECLARE
V_DNAME VARCHAR2(20) := 'DDD';
    V_LOC VARCHAR2(20) := 'CHANGSHA';
BEGIN
    P_ADD_DEPT(V_DNAME,V_LOC);
END;

--存储过程综合案例
--返回指定部门的员工信息：编码，姓名，部门编码，部门名称，工资，员工所在部门平均工资
--需求分析
--1.输入体 ：部门编码
--2 输出体 ： 姓名，部门编码，部门名称，工资，员工所在部门平均工资

SELECT E.EMPNO,E.ENAME ,E.DEPTNO,D.DNAME ,E.SAL,C.AVG_SAL FROM EMP  E,
(SELECT DEPTNO,AVG(SAL) AVG_SAL FROM EMP GROUP BY DEPTNO) C ,DEPT D
WHERE E.DEPTNO = C.DEPTNO AND E.DEPTNO = D.DEPTNO

--创建视图
CREATE OR REPLACE VIEW VI_EMP_AVGSAL
AS
SELECT E.EMPNO,E.ENAME ,E.DEPTNO,D.DNAME ,E.SAL,C.AVG_SAL FROM EMP  E,
(SELECT DEPTNO,AVG(SAL) AVG_SAL FROM EMP GROUP BY DEPTNO) C ,DEPT D
WHERE E.DEPTNO = C.DEPTNO AND E.DEPTNO = D.DEPTNO



SELECT * FROM VI_EMP_AVGSAL WHERE DEPTNO =10

--创建存储过程
CREATE OR REPLACE PROCEDURE P_EMP_AVGSAL
(V_DEPTNO IN NUMBER , V_EMPAVG OUT SYS_REFCURSOR)  --当游标做输出参数的时候类型为SYS_REFCURSOR
AS
 V_COUNT NUMBER;
 V_EMP SCOTT.VI_EMP_AVGSAL%ROWTYPE;   --VI_EMP_AVGSAL 视图
BEGIN
OPEN V_EMPAVG FOR 'SELECT * FROM VI_EMP_AVGSAL WHERE DEPTNO = :V_DEPTNO' USING V_DEPTNO;
END;


DECLARE
V_DEPTNO NUMBER;
  TYPE T_EMPAVG IS REF CURSOR;
  C_EMPAVG T_EMPAVG;
  V_AVGSALROW SCOTT.VI_EMP_AVGSAL%ROWTYPE;
BEGIN
  V_DEPTNO := '&请输入部门编码';
  P_EMP_AVGSAL(V_DEPTNO,C_EMPAVG);
  LOOP
FETCH C_EMPAVG INTO V_AVGSALROW;
    EXIT WHEN C_EMPAVG%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('V_AVGSALRO.EMPNO  ' || V_AVGSALROW.EMPNO );
    DBMS_OUTPUT.PUT_LINE('V_AVGSALRO.AVG_SAL ' || V_AVGSALROW.AVG_SAL );
END LOOP;

  IF C_EMPAVG%ISOPEN THEN
     CLOSE C_EMPAVG;
END IF;
END ;




























