--表管理
--数据库定于语言 （DDL)   CRATE ALTER DROP
--创建表
CREATE TABLE STUDENT(
                        S_ID NUMBER(10),
                        S_NAME VARCHAR2(20),
                        S_JOIN_DATE DATE,
                        S_HOBBIES VARCHAR2(20)
);

--修改表
--新增一个字段
ALTER TABLE STUDENT ADD S_AGE1 NUMBER(10);

--删除一个字段
ALTER TABLE STUDENT DROP COLUMN S_AGE1;

--修改一个字段
ALTER TABLE STUDENT RENAME COLUMN S_JOIN_DATE TO S_DATE;

--修改字段类型
ALTER TABLE STUDENT MODIFY S_HOBBIES VARCHAR2(10);

--修改表的名称
RENAME STUDENTS TO STUDENT;
ALTER TABLE STUDENT RENAME TO STUDENTS;

--删除表
DROP TABLE STUDENTS;

SELECT * FROM STUDENTS;

--插入数据
INSERT INTO STUDENT VALUES(1,'AMO',SYSDATE,'学习');
INSERT INTO STUDENT (S_ID,S_NAME) VALUES(1,'季黎明');

INSERT INTO STUDENT
SELECT 2,'梁国栋',SYSDATE,'学习' FROM DUAL UNION ALL
SELECT 3,'灼灼',SYSDATE,'学习' FROM DUAL UNION ALL
SELECT 4,'火花',SYSDATE,'学习' FROM DUAL UNION ALL
SELECT 5,'可乐',SYSDATE,'学习' FROM DUAL ;

SELECT * FROM STUDENT;
INSERT INTO STUDENT VALUES(7,'花颜','2018-3月-03','学习');
INSERT INTO STUDENT VALUES(6,'色彩','2018-02-03','学习');

--修改插入时间格式
ALTER SESSION SET NLS_DATE_FORMAT ='YYYY-MM-DD';

--修改数据   连接条件:AND  并且  OR  或者
UPDATE STUDENT SET S_ID=1 WHERE S_NAME ='SUN';
UPDATE STUDENT SET S_HOBBIES = S_HOBBIES || ',丢灼灼' WHERE S_ID=3;  --|| sql的连接符
UPDATE STUDENT SET S_HOBBIES = S_HOBBIES || ',清蒸灼灼' WHERE S_ID = 1 AND S_NAME='AMO';
UPDATE STUDENT SET S_HOBBIES = S_HOBBIES || '黑客' WHERE S_ID = 2 OR S_ID =4;
--删除语句
DELETE FROM STUDENT WHERE S_ID=7;





















